apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: blgianinis/argocd-teste
  newTag: e1ed6f8ec5badadb495cdde442f3592fa723fd67
