apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: blgianinis/argocd-teste
  newTag: 36fdc1772ea2791f10c8c15d276893844a50a0da
